packages:
  - ./apps/*
  - ./packages/*

catalog:
  '@acdh-oeaw/eslint-config': ^2.0.10
  '@acdh-oeaw/eslint-config-next': ^3.0.0
  '@acdh-oeaw/eslint-config-node': ^2.0.10
  '@acdh-oeaw/eslint-config-playwright': ^2.0.12
  '@acdh-oeaw/eslint-config-react': ^2.0.14
  '@acdh-oeaw/eslint-config-tailwindcss': ^3.0.2
  '@acdh-oeaw/lib': ^0.3.5
  '@acdh-oeaw/prettier-config': ^2.0.1
  '@acdh-oeaw/tsconfig': ^1.5.1
  '@acdh-oeaw/tsconfig-lib': ^1.3.0
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.7
  '@next/eslint-plugin-next': canary
  '@playwright/test': ^1.55.1
  '@scalar/nextjs-api-reference': ^0.8.20
  '@scalar/openapi-types': ^0.3.7
  '@tailwindcss/postcss': ^4.1.13
  '@types/node': ^22.18.6
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@valibot/to-json-schema': ^1.3.0
  eslint: ^9.36.0
  eslint-config-flat-gitignore: ^2.1.0
  globals: ^16.4.0
  is-in-ci: ^2.0.0
  lint-staged: ^16.2.1
  next: canary
  node: ^22.20.0
  npm-run-all2: ^8.0.4
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.1.13
  tsdown: ^0.15.4
  tsx: ^4.20.6
  turbo: ^2.5.8
  typescript: ^5.9.2
  valibot: 1.1.0

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - node
  - sharp
  - simple-git-hooks
  - unrs-resolver

shellEmulator: true

strictDepBuilds: true
