packages:
  - ./apps/*
  - ./packages/*

catalog:
  '@acdh-oeaw/eslint-config': ^2.0.10
  '@acdh-oeaw/eslint-config-next': ^4.0.3
  '@acdh-oeaw/eslint-config-node': ^2.0.10
  '@acdh-oeaw/eslint-config-playwright': ^2.0.12
  '@acdh-oeaw/eslint-config-react': ^3.0.2
  '@acdh-oeaw/eslint-config-tailwindcss': ^3.0.2
  '@acdh-oeaw/lib': ^0.3.5
  '@acdh-oeaw/prettier-config': ^2.0.1
  '@acdh-oeaw/tsconfig': ^1.5.1
  '@acdh-oeaw/tsconfig-lib': ^1.3.0
  '@arethetypeswrong/core': ^0.18.2
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.7
  '@next/eslint-plugin-next': ^16.0.3
  '@playwright/test': ^1.56.1
  '@scalar/nextjs-api-reference': ^0.9.1
  '@scalar/openapi-types': ^0.5.1
  '@tailwindcss/postcss': ^4.1.17
  '@types/node': ^24.10.1
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  '@valibot/to-json-schema': ^1.3.0
  eslint: ^9.39.1
  eslint-config-flat-gitignore: ^2.1.0
  globals: ^16.5.0
  is-in-ci: ^2.0.0
  lint-staged: ^16.2.6
  next: ^16.0.3
  node: runtime:^24.11.1
  npm-run-all2: ^8.0.4
  prettier: ^3.6.2
  react: ^19.2.0
  react-dom: ^19.2.0
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.1.17
  tsdown: ^0.16.4
  tsx: ^4.20.6
  turbo: ^2.6.1
  typescript: ^5.9.3
  valibot: ^1.1.0

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - node
  - sharp
  - simple-git-hooks
  - unrs-resolver

shellEmulator: true

strictDepBuilds: true
